### ISSUE TITLE
Flexbility of apiversion in Custom Resources

### ISSUE THREAD

**Issue by dalees** [stackhpc/magnum-capi-helm#25]
When CAPI or CAPO providers release new versions, we'll want to use a newer `apiversion` for Custom Resources.

The current Magnum driver implements K8s API client with Classes that have a [fixed value for `api_version`](https://github.com/stackhpc/magnum-capi-helm/blob/6726c7c46d3cac44990bc66bbad7b3dd44f72c2b/magnum_capi_helm/kubernetes.py#L253). This makes it easy to request directly into the K8s API for named values that match these objects.

However, when upgrading CAPI/CAPO we'll have some resources in the CAPI management cluster with the older apiversion (eg. `cluster.x-k8s.io/v1beta1`) and we'll update Helm charts to start creating new apiversion objects (eg. `cluster.x-k8s.io/v1beta2`).

Magnum will be regularly fetching these resources by apiversion and name. This will either fail to fetch the new ones (with an old Magnum deployment), or fail to fetch the old ones. A re-creation and cutover event must take place to be able to use the new `cluster.x-k8s.io/v1beta2` apiversion (which will need to happen on CAPI management Resources, Magnum codebase and Helm charts simultaneously).

The solution to this **may** be to use [K8s API discovery](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-discovery), so we end up fetching our example `Cluster` resources by name. Libraries such as https://github.com/kubernetes-client support this discovery.

**Comment by dalees** [comment]
@mkjpryor I suspect you'll have some helpful background on why `kubernetes.py` is as it is, and hopefully some ideas on alternative libraries or upgrade strategies.

**Comment by mkjpryor** [comment]
We should discover the current preferred version from the Kubernetes API - this is actually quite easy. For example, this is how it is done in the asyncio client that we use in all the Azimuth components:

https://github.com/stackhpc/easykube/blob/main/easykube/kubernetes/client/client.py#L55

**Comment by mnasiadka** [comment]
Please raise that issue under https://bugs.launchpad.net/magnum - we're archiving that repository since it was moved to OpenStack governance.
