### ISSUE TITLE
Procedure for coe cluster creation not work

### ISSUE THREAD

**Issue by mathgonzlez** [stackhpc/magnum-capi-helm#53]
Hi, im trying to use the procedure you describe for create coe cluster but i see this issues:

`2024-03-20 00:54:41.932 18 ERROR oslo_messaging.rpc.server [None req-f3c68b4e-db88-4da9-b8a6-1c71db75b340 e2a1f54c86914966b4ca014324799832 01adb0aae1b94bd493311c94456643a4 - - default -] Exception during message handling: KeyError: 'kube_tag'`

When i add the tag for image that you recomend (1.28 based) i see this error in magnum log:
`2024-03-19 23:47:45.794 18 ERROR oslo_messaging.rpc.server ValueError: Unsupported Kubernetes version: 1.28.3. Please specify a supported version in the cluster template.`

As a workaround i change de tag version to a supported (1.27 based) but the cluster failed to create after control-plane boot.

Im using Kolla-ansible as osp deployment

Thanks!

**Comment by mnasiadka** [comment]
Hello @mathgonzlez - the repository has been moved to official OpenStack governance, please ask that question again either on #openstack-containers on OFTC IRC or raise a bug request under https://bugs.launchpad.net/magnum
